# Generated by Django 4.2.13 on 2024-07-03 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dealapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="deal",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
