# Generated by Django 4.2.13 on 2024-07-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dealapp", "0002_deal_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserDeal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
                ("deal_id", models.IntegerField()),
            ],
        ),
    ]
